In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\MUNNA\Downloads\archive (12)\fake_or_real_news.csv")
df

Unnamed: 0                                              title  \
0           8476                       You Can Smell Hillary’s Fear   
1          10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2           3608        Kerry to go to Paris in gesture of sympathy   
3          10142  Bernie supporters on Twitter erupt in anger ag...   
4            875   The Battle of New York: Why This Primary Matters   
...          ...                                                ...   
6330        4490  State Department says it can't find emails fro...   
6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333        4021  In Ethiopia, Obama seeks progress on peace, se...   
6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4     It's primary day in New York and front-runners...  REAL  
...                                                 ...   ...  
6330  The State Department told the Republican Natio...  REAL  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL  

[6335 rows x 4 columns]

In [5]:
df['labels'] = df['label'].map({'FAKE':1, 'REAL': 0})

In [6]:
df

Unnamed: 0                                              title  \
0           8476                       You Can Smell Hillary’s Fear   
1          10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2           3608        Kerry to go to Paris in gesture of sympathy   
3          10142  Bernie supporters on Twitter erupt in anger ag...   
4            875   The Battle of New York: Why This Primary Matters   
...          ...                                                ...   
6330        4490  State Department says it can't find emails fro...   
6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333        4021  In Ethiopia, Obama seeks progress on peace, se...   
6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  labels  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE       1  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE       1  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL       0  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE       1  
4     It's primary day in New York and front-runners...  REAL       0  
...                                                 ...   ...     ...  
6330  The State Department told the Republican Natio...  REAL       0  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE       1  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE       1  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL       0  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL       0  

[6335 rows x 5 columns]

In [7]:
df = df.drop('label', axis = 1)

In [8]:
df

Unnamed: 0                                              title  \
0           8476                       You Can Smell Hillary’s Fear   
1          10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2           3608        Kerry to go to Paris in gesture of sympathy   
3          10142  Bernie supporters on Twitter erupt in anger ag...   
4            875   The Battle of New York: Why This Primary Matters   
...          ...                                                ...   
6330        4490  State Department says it can't find emails fro...   
6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333        4021  In Ethiopia, Obama seeks progress on peace, se...   
6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text  labels  
0     Daniel Greenfield, a Shillman Journalism Fello...       1  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...       1  
2     U.S. Secretary of State John F. Kerry said Mon...       0  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...       1  
4     It's primary day in New York and front-runners...       0  
...                                                 ...     ...  
6330  The State Department told the Republican Natio...       0  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...       1  
6332   Anti-Trump Protesters Are Tools of the Oligar...       1  
6333  ADDIS ABABA, Ethiopia —President Obama convene...       0  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...       0  

[6335 rows x 4 columns]

In [9]:
df.isnull().sum()

Unnamed: 0    0
title         0
text          0
labels        0
dtype: int64

In [11]:
df.shape

(6335, 4)

In [13]:
X = df.drop('labels', axis =1)
y = df['labels']

In [14]:
X.shape

(6335, 3)

In [15]:
y.shape

(6335,)

### Importing the required libraries

In [88]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM, Bidirectional
from tensorflow.keras.layers import Dense

### Initializing the vocabulary size

In [17]:
voc_size = 5000

In [18]:
message = X.copy()

In [20]:
message['title'][1]

'Watch The Exact Moment Paul Ryan Committed Political Suicide At A Trump Rally (VIDEO)'

In [21]:
message

Unnamed: 0                                              title  \
0           8476                       You Can Smell Hillary’s Fear   
1          10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2           3608        Kerry to go to Paris in gesture of sympathy   
3          10142  Bernie supporters on Twitter erupt in anger ag...   
4            875   The Battle of New York: Why This Primary Matters   
...          ...                                                ...   
6330        4490  State Department says it can't find emails fro...   
6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333        4021  In Ethiopia, Obama seeks progress on peace, se...   
6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text  
0     Daniel Greenfield, a Shillman Journalism Fello...  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  
2     U.S. Secretary of State John F. Kerry said Mon...  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  
4     It's primary day in New York and front-runners...  
...                                                 ...  
6330  The State Department told the Republican Natio...  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  
6332   Anti-Trump Protesters Are Tools of the Oligar...  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  

[6335 rows x 3 columns]

In [22]:
message.reset_index(inplace = True)

In [23]:
message

index  Unnamed: 0                                              title  \
0         0        8476                       You Can Smell Hillary’s Fear   
1         1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2         2        3608        Kerry to go to Paris in gesture of sympathy   
3         3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         4         875   The Battle of New York: Why This Primary Matters   
...     ...         ...                                                ...   
6330   6330        4490  State Department says it can't find emails fro...   
6331   6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332   6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333   6333        4021  In Ethiopia, Obama seeks progress on peace, se...   
6334   6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text  
0     Daniel Greenfield, a Shillman Journalism Fello...  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  
2     U.S. Secretary of State John F. Kerry said Mon...  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  
4     It's primary day in New York and front-runners...  
...                                                 ...  
6330  The State Department told the Republican Natio...  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  
6332   Anti-Trump Protesters Are Tools of the Oligar...  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  

[6335 rows x 4 columns]

## Text Preprocessing part

In [24]:
import re
import nltk
from nltk.corpus import stopwords

In [25]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\MUNNA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [26]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0,len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = " ".join(review)
    corpus.append(review)

In [29]:
corpus[1]

'watch exact moment paul ryan commit polit suicid trump ralli video'

## After the preprocessing we apply ONE HOT ENCODER

In [32]:
onehot_rep = [one_hot(word, voc_size) for word in corpus]
onehot_rep

[[1697, 2792, 4492],
 [3628, 3965, 1565, 2191, 1549, 353, 68, 3621, 3340, 2947, 861],
 [4603, 4661, 2506, 1922, 2144],
 [59, 2682, 3362, 4319, 4972, 4945, 420, 4662],
 [1800, 4640, 3290, 5, 1179],
 [2343, 2994],
 [2991, 431, 3628, 107, 1146, 4176],
 [2203, 697, 267],
 [2908, 3148, 3340, 3820, 3760, 4024, 3713],
 [700, 1758, 1725, 4640, 340, 1359, 2322, 608, 4466],
 [1162, 3820, 3632, 4667, 1556, 1333, 2792, 3820, 1571],
 [656, 3340, 1256, 2439, 2524, 4781, 2966, 44, 3039, 3529],
 [1798, 1999, 2644, 3419, 4313, 713, 3248, 1009, 861],
 [695, 3347, 2734, 797, 921],
 [3340, 3056, 689, 171],
 [4111, 2344, 3695],
 [297, 2105, 2860, 2792, 3198, 396, 3423, 328, 1604],
 [2792, 3820, 3570, 660, 3347, 856, 4402, 3278, 1972, 4209, 2857, 407, 3248],
 [700, 4683, 2860, 3241],
 [1430, 1029, 1337, 1742, 1009, 2929, 3347],
 [611, 2770, 3340, 960, 1158, 939],
 [1575, 625, 4400, 2242, 2330, 1905, 343, 1477, 2982],
 [2792, 3820, 1725, 541, 1726, 3559, 662],
 [4640, 2884, 794, 1655, 3586, 92, 3340, 4135],


In [34]:
onehot_rep[1]

[3628, 3965, 1565, 2191, 1549, 353, 68, 3621, 3340, 2947, 861]

## Padding Representation

In [44]:
sent_length = 20

In [45]:
embedded_docs = pad_sequences(onehot_rep, padding = "pre", maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 ... 1697 2792 4492]
 [   0    0    0 ... 3340 2947  861]
 [   0    0    0 ... 2506 1922 2144]
 ...
 [   0    0    0 ... 3350  625  449]
 [   0    0    0 ...  705 2629 2460]
 [   0    0    0 ... 4022 3340 1179]]


# Creating the model [embedding(for semantic meaning) and LSTM]

In [51]:
## Creating model
embedding_vector_features=40 ##features representation

#embedding
model=Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=embedding_vector_features, input_length=sent_length))

#LSTM model
model.add(LSTM(100))

#now the output is ready for a ANN input
model.add(Dense(1,activation='sigmoid'))

#Manually building the model
model.build(input_shape=(None, sent_length))

#compiling
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


In [52]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)              │ (None, 20, 40)              │         200,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_7 (LSTM)                        │ (None, 100)                 │          56,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1)                   │             101 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

In [53]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [55]:
X_final.shape

(6335, 20)

In [58]:
y_final.shape

(6335,)

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.3, random_state=42)

# Model Training

In [61]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs = 10, batch_size = 100)

Epoch 1/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 4s 77ms/step - accuracy: 0.9836 - loss: 0.0549 - val_accuracy: 0.7501 - val_loss: 1.0755
Epoch 2/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 6s 89ms/step - accuracy: 0.9814 - loss: 0.0642 - val_accuracy: 0.7549 - val_loss: 1.1637
Epoch 3/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - accuracy: 0.9893 - loss: 0.0445 - val_accuracy: 0.7585 - val_loss: 1.4052
Epoch 4/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.9906 - loss: 0.0340 - val_accuracy: 0.7538 - val_loss: 1.4705
Epoch 5/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - accuracy: 0.9947 - loss: 0.0217 - val_accuracy: 0.7528 - val_loss: 1.6790
Epoch 6/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 5s 72ms/step - accuracy: 0.9963 - loss: 0.0139 - val_accuracy: 0.7538 - val_loss: 1.5926
Epoch 7/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 3s 75ms/step - accuracy: 0.9972 - loss: 0.0152 - val_accuracy: 0.7559 - val_loss: 1.5253
Epoch 8/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.9958 - loss: 0.0172 - val_accuracy: 0.7391 - v

## Performance Metrics and Accuracy

In [66]:
y_pred = model.predict(X_test)

60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step


array([[9.989532e-01],
       [1.000000e+00],
       [9.999963e-01],
       ...,
       [9.998876e-01],
       [5.504368e-01],
       [1.819591e-06]], dtype=float32)

In [77]:
y_pred = np.where(y_pred >0.5, 1,0)

In [78]:
from sklearn.metrics import confusion_matrix

In [79]:
confusion_matrix(y_test,y_pred)

array([[704, 229],
       [228, 740]], dtype=int64)

In [75]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7596002104155708

In [76]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.76      0.75      0.75       933
           1       0.76      0.76      0.76       968

    accuracy                           0.76      1901
   macro avg       0.76      0.76      0.76      1901
weighted avg       0.76      0.76      0.76      1901



## Adding droput for improving the accuracy(Reduces overfitting)

In [80]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.build(input_shape=(None, sent_length))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

C:\Users\MUNNA\tf-env\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [81]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs = 10, batch_size = 100)

Epoch 1/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - accuracy: 0.5320 - loss: 0.6905 - val_accuracy: 0.7370 - val_loss: 0.6421
Epoch 2/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 3s 75ms/step - accuracy: 0.7224 - loss: 0.5832 - val_accuracy: 0.7533 - val_loss: 0.4972
Epoch 3/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 3s 75ms/step - accuracy: 0.8352 - loss: 0.3939 - val_accuracy: 0.7833 - val_loss: 0.4758
Epoch 4/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - accuracy: 0.8819 - loss: 0.2962 - val_accuracy: 0.7806 - val_loss: 0.4936
Epoch 5/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.9210 - loss: 0.2196 - val_accuracy: 0.7749 - val_loss: 0.5488
Epoch 6/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 3s 76ms/step - accuracy: 0.9305 - loss: 0.1898 - val_accuracy: 0.7749 - val_loss: 0.6092
Epoch 7/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.9391 - loss: 0.1661 - val_accuracy: 0.7638 - val_loss: 0.6794
Epoch 8/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 6s 98ms/step - accuracy: 0.9480 - loss: 0.1373 - val_accuracy: 0.7680 - 

In [82]:
y_pred = model.predict(X_test)

60/60 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step


In [84]:
y_pred = np.where(y_pred >0.5, 1,0)

In [85]:
confusion_matrix(y_test,y_pred)

array([[725, 208],
       [241, 727]], dtype=int64)

In [86]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.75      0.78      0.76       933
           1       0.78      0.75      0.76       968

    accuracy                           0.76      1901
   macro avg       0.76      0.76      0.76      1901
weighted avg       0.76      0.76      0.76      1901



# BIDIRECTIONAL LSTM RNN

## Applying bidirectional lstm rnn to the above data

In [89]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(Bidirectional(LSTM(100)))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.build(input_shape=(None, sent_length))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

C:\Users\MUNNA\tf-env\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [90]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs = 10, batch_size = 100)

Epoch 1/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 14s 111ms/step - accuracy: 0.5336 - loss: 0.6887 - val_accuracy: 0.7354 - val_loss: 0.6119
Epoch 2/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.7570 - loss: 0.5167 - val_accuracy: 0.7701 - val_loss: 0.4800
Epoch 3/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - accuracy: 0.8714 - loss: 0.3166 - val_accuracy: 0.7775 - val_loss: 0.5146
Epoch 4/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - accuracy: 0.9087 - loss: 0.2390 - val_accuracy: 0.7733 - val_loss: 0.5556
Epoch 5/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - accuracy: 0.9253 - loss: 0.1951 - val_accuracy: 0.7528 - val_loss: 0.6826
Epoch 6/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.9413 - loss: 0.1715 - val_accuracy: 0.7638 - val_loss: 0.6518
Epoch 7/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 4s 85ms/step - accuracy: 0.9507 - loss: 0.1462 - val_accuracy: 0.7507 - val_loss: 0.7789
Epoch 8/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 4s 84ms/step - accuracy: 0.9580 - loss: 0.1229 - val_accuracy: 0.7422 -

In [91]:
y_pred = model.predict(X_test)

60/60 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step


In [92]:
y_pred = np.where(y_pred >0.5, 1,0)

In [93]:
confusion_matrix(y_test,y_pred)

array([[760, 173],
       [302, 666]], dtype=int64)

In [94]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.72      0.81      0.76       933
           1       0.79      0.69      0.74       968

    accuracy                           0.75      1901
   macro avg       0.75      0.75      0.75      1901
weighted avg       0.76      0.75      0.75      1901



In [ ]:
The steps for this project are:
- dataset
- cleaning the original data
- independent and dependent features
- text preprocessing 1)stemming 2)stopwords
- OHE
- applying padding layer to OHE
- Creating the model embedding(for semantic meaning) and LSTM
- after the model is ready we decide our final train and test data from embedded_docs
- then we split this final data into train and test and fit the model
- then we predict and evaluate the performance metrics


- apply dropout while buidling the model to avoid overfit
- apply bidirectional lstm rnn if required